language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"

before_install:
  - sudo add-apt-repository ppa:glance-core/trunk
  - sudo apt-get update -qq
  - sudo apt-get install glance python-dev libffi-dev -y

install:
  - pip install -rtests/requirements.txt
  - pip install .

script: python setup.py nosetests
